- name: modify repository
  apt_repository:
    repo: "deb [arch=amd64] http://packages.treasuredata.com/2/ubuntu/trusty/ trusty contrib"
    state: present

- name: install td-agent
  apt:
    name: "td-agent={{ td_agent_version }}*"
    state: present
    force: yes

- name: install fluent plugins
  shell: "/opt/td-agent/usr/sbin/td-agent-gem install --no-ri --no-rdoc {{ item }}"
  with_items: "{{ td_agent_plugins }}"

- name: modify sysconfig
  template:
    src: sysconfig
    dest: /etc/default/td-agent
    owner: root
    group: root
    mode: 0644
  notify: restart td-agent

- name: modify td-agent.conf
  template:
    src: td-agent.conf
    dest: /etc/td-agent/td-agent.conf
    owner: root
    group: root
    mode: 0644
  notify: restart td-agent

- name: create custom config directory
  file:
    path: /etc/td-agent/conf.d/
    state: directory
    owner: root
    group: root
    mode: 0755

- name: td-agent is enabled
  service:
    name: td-agent
    state: started
    enabled: yes
